<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-9J8R4PP" failures="3" tests="7" name="Test1" time="30.252" errors="0" timestamp="2022-09-19T13:31:47 IST">
  <testcase classname="appiumtests.merchantApp_testNG" name="email" time="9.76"/>
  <testcase classname="appiumtests.merchantApp_testNG" name="clickNextEmail" time="0.786"/>
  <testcase classname="appiumtests.merchantApp_testNG" name="enterPassword" time="14.154"/>
  <testcase classname="appiumtests.merchantApp_testNG" name="failTest1" time="0.022">
    <failure type="java.lang.AssertionError" message="expected [1234] but found [123]">
      <![CDATA[java.lang.AssertionError: expected [1234] but found [123]
at appiumtests.merchantApp_testNG.failTest1(merchantApp_testNG.java:82)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 37 stack frames]]>
    </failure>
  </testcase> <!-- failTest1 -->
  <testcase classname="appiumtests.merchantApp_testNG" name="failTest2" time="0.011">
    <failure type="java.lang.AssertionError" message="expected [12345] but found [1234]">
      <![CDATA[java.lang.AssertionError: expected [12345] but found [1234]
at appiumtests.merchantApp_testNG.failTest2(merchantApp_testNG.java:106)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 37 stack frames]]>
    </failure>
  </testcase> <!-- failTest2 -->
  <testcase classname="appiumtests.merchantApp_testNG" name="failTest3" time="0.011">
    <failure type="java.lang.AssertionError" message="expected [12345] but found [1234aa]">
      <![CDATA[java.lang.AssertionError: expected [12345] but found [1234aa]
at appiumtests.merchantApp_testNG.failTest3(merchantApp_testNG.java:115)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 37 stack frames]]>
    </failure>
  </testcase> <!-- failTest3 -->
  <testcase classname="appiumtests.merchantApp_testNG" name="failTest5" time="0.01"/>
</testsuite> <!-- Test1 -->
